# Generated by Django 5.2.8 on 2026-07-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0002_auditlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalevaluation",
            name="committee_doctors",
        ),
        migrations.RemoveField(
            model_name="personalquestionnaire",
            name="patient",
        ),
        migrations.AlterModelOptions(
            name="medicalevaluation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={},
        ),
        migrations.RemoveField(
            model_name="medicalevaluation",
            name="committee_members",
        ),
        migrations.RemoveField(
            model_name="medicalevaluation",
            name="decision_reason",
        ),
        migrations.RemoveField(
            model_name="medicalevaluation",
            name="diagnosis",
        ),
        migrations.RemoveField(
            model_name="medicalevaluation",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="medicalevaluation",
            name="injury_degree",
        ),
        migrations.RemoveField(
            model_name="medicalevaluation",
            name="medical_notes",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="address",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="children_count",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="companion_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="companion_phone",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="father_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="has_identity_card",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="has_injury_document",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="has_medical_report",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="has_military_card",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="has_photos",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="health_condition",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="identity_card_image",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="injury_document_image",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="injury_place",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="medical_report_image",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="military_card_image",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="military_number",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="military_unit",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="mother_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="other_documents",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="place_of_birth",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="previous_details",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="rank",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="reception_notes",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="social_status",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="medicalevaluation",
            name="cause_and_location",
            field=models.CharField(
                default="غير محدد", max_length=255, verbose_name="سبب ومكان الإصابة"
            ),
        ),
        migrations.AddField(
            model_name="medicalevaluation",
            name="considered_injury_category",
            field=models.CharField(
                default="غير محدد", max_length=200, verbose_name="فئة الإصابة المعتبرة"
            ),
        ),
        migrations.AddField(
            model_name="medicalevaluation",
            name="considered_injury_type",
            field=models.CharField(
                default="غير محدد", max_length=200, verbose_name="نوع الإصابة المعتبرة"
            ),
        ),
        migrations.AddField(
            model_name="medicalevaluation",
            name="doctor_name",
            field=models.CharField(
                default="غير محدد", max_length=150, verbose_name="اسم عضو اللجنة الطبية"
            ),
        ),
        migrations.AddField(
            model_name="medicalevaluation",
            name="is_eligible",
            field=models.BooleanField(default=False, verbose_name="مستحق"),
        ),
        migrations.AddField(
            model_name="patient",
            name="current_residence",
            field=models.CharField(
                default="غير محدد", max_length=200, verbose_name="السكن الحالي"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="extinct_faction_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="الفصيل المندثر"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="full_name",
            field=models.CharField(
                default="غير محدد", max_length=150, verbose_name="الاسم الثلاثي"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="injury_category",
            field=models.CharField(
                default="غير محدد", max_length=200, verbose_name="فئة الإصابة"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="injury_details",
            field=models.TextField(default="غير محدد", verbose_name="تفاصيل الإصابة"),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_extinct_factions",
            field=models.BooleanField(default=False, verbose_name="فصائل مندثرة"),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_medical_evaluation",
            field=models.BooleanField(default=False, verbose_name="تقييم طبي"),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_ministry_sent",
            field=models.BooleanField(default=False, verbose_name="مرسل وزارة"),
        ),
        migrations.AddField(
            model_name="patient",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="اللقب"
            ),
        ),
        migrations.AlterField(
            model_name="medicalevaluation",
            name="decision",
            field=models.CharField(
                choices=[
                    ("ACCEPTED", "قبول"),
                    ("REJECTED", "رفض"),
                    ("SUSPENDED", "تعليق"),
                ],
                default="ACCEPTED",
                max_length=20,
                verbose_name="قرار اللجنة",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ الميلاد"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="injury_type",
            field=models.CharField(
                default="غير محدد", max_length=200, verbose_name="نوع الإصابة"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="الرقم الذاتي",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رقم الهاتف"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNDER_MEDICAL_REVIEW", "قيد التقييم الطبي"),
                    ("ACCEPTED", "مقبول"),
                    ("REJECTED", "مرفوض"),
                    ("SUSPENDED", "معلّق"),
                    ("ACTIVATION_COMPLETED", "مكتمل التفعيل"),
                ],
                default="UNDER_MEDICAL_REVIEW",
                max_length=30,
                verbose_name="حالة الملف",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="tracking_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="الرقم التسلسلي",
            ),
        ),
        migrations.CreateModel(
            name="Activation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=False, verbose_name="تفعيل إلزامي"),
                ),
                (
                    "desired_work",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="العمل الذي ترغب به",
                    ),
                ),
                (
                    "witness_1_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="اسم شاهد أول",
                    ),
                ),
                (
                    "witness_1_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="رقم هاتف الشاهد الأول",
                    ),
                ),
                (
                    "witness_1_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم الذاتي للشاهد الأول",
                    ),
                ),
                (
                    "witness_2_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="اسم شاهد ثاني",
                    ),
                ),
                (
                    "witness_2_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="رقم هاتف الشاهد الثاني",
                    ),
                ),
                (
                    "witness_2_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم الذاتي للشاهد الثاني",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التفعيل"
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation",
                        to="reception.patient",
                        verbose_name="المصاب",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
        migrations.DeleteModel(
            name="CommitteeDoctor",
        ),
        migrations.DeleteModel(
            name="PersonalQuestionnaire",
        ),
    ]
