# Generated by Django 5.2.8 on 2026-07-04 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0003_remove_medicalevaluation_committee_doctors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activation",
            name="witness_1_phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رقم الهاتف يجب أن يبدأ بـ 09 وأن يتكوّن من 10 خانات فقط.",
                        regex="^09\\d{8}$",
                    )
                ],
                verbose_name="رقم هاتف الشاهد الأول",
            ),
        ),
        migrations.AlterField(
            model_name="activation",
            name="witness_2_phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رقم الهاتف يجب أن يبدأ بـ 09 وأن يتكوّن من 10 خانات فقط.",
                        regex="^09\\d{8}$",
                    )
                ],
                verbose_name="رقم هاتف الشاهد الثاني",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رقم الهاتف يجب أن يبدأ بـ 09 وأن يتكوّن من 10 خانات فقط.",
                        regex="^09\\d{8}$",
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
    ]
