# Generated by Django 5.2.8 on 2026-07-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0004_alter_activation_witness_1_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalevaluation",
            name="cause_and_location",
            field=models.CharField(
                default="", max_length=255, verbose_name="سبب ومكان الإصابة"
            ),
        ),
        migrations.AlterField(
            model_name="medicalevaluation",
            name="considered_injury_category",
            field=models.CharField(
                default="", max_length=200, verbose_name="فئة الإصابة المعتبرة"
            ),
        ),
        migrations.AlterField(
            model_name="medicalevaluation",
            name="considered_injury_type",
            field=models.CharField(
                default="", max_length=200, verbose_name="نوع الإصابة المعتبرة"
            ),
        ),
        migrations.AlterField(
            model_name="medicalevaluation",
            name="doctor_name",
            field=models.CharField(
                default="", max_length=150, verbose_name="اسم عضو اللجنة الطبية"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="current_residence",
            field=models.CharField(
                default="", max_length=200, verbose_name="السكن الحالي"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="full_name",
            field=models.CharField(
                default="", max_length=150, verbose_name="الاسم الثلاثي"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="injury_category",
            field=models.CharField(
                default="", max_length=200, verbose_name="فئة الإصابة"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="injury_details",
            field=models.TextField(default="", verbose_name="تفاصيل الإصابة"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="injury_type",
            field=models.CharField(
                default="", max_length=200, verbose_name="نوع الإصابة"
            ),
        ),
    ]
