# Generated by Django 5.2.8 on 2026-07-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0005_alter_medicalevaluation_cause_and_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="injury_category",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="injury_date",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="injury_details",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="injury_type",
        ),
        migrations.AddField(
            model_name="medicalevaluation",
            name="injury_category",
            field=models.CharField(
                default="", max_length=200, verbose_name="فئة الإصابة"
            ),
        ),
        migrations.AddField(
            model_name="medicalevaluation",
            name="injury_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ الإصابة"),
        ),
        migrations.AddField(
            model_name="medicalevaluation",
            name="injury_details",
            field=models.TextField(default="", verbose_name="تفاصيل الإصابة"),
        ),
        migrations.AddField(
            model_name="medicalevaluation",
            name="injury_type",
            field=models.CharField(
                default="", max_length=200, verbose_name="نوع الإصابة"
            ),
        ),
    ]
