# Generated by Django 5.2.8 on 2026-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0006_remove_patient_injury_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalevaluation",
            name="decision",
        ),
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNDER_MEDICAL_REVIEW", "قيد التقييم الطبي"),
                    ("READY_FOR_ACTIVATION", "قيد التفعيل"),
                    ("ACCEPTED", "مقبول"),
                ],
                default="UNDER_MEDICAL_REVIEW",
                max_length=30,
                verbose_name="حالة الملف",
            ),
        ),
    ]
