# Generated by Django 5.2.8 on 2026-07-05 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0007_remove_medicalevaluation_decision_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="اسم الطبيب / عضو اللجنة",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="medicalevaluation",
            name="doctor_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="reception.doctor",
                verbose_name="اسم عضو اللجنة الطبية",
            ),
        ),
    ]
